name: Java CI with Maven Github Action Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Run Test Cases
        run: mvn '-Dtest=*Test' verify -Djacoco.destFile=exportJacoco/jacoco-slow-it.exec

      - name: Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload jacoco exec test results
        uses: actions/upload-artifact@v2
        with:
          name: tests-jacoco
          path: exportJacoco/jacoco-slow-it.exec
